Update deploy_to_pages.yml

diff --git a/.github/workflows/deploy_to_pages.yml b/.github/workflows/deploy_to_pages.yml
--- a/.github/workflows/deploy_to_pages.yml
+++ b/.github/workflows/deploy_to_pages.yml
@@ -15,7 +15,9 @@ jobs:
           node-version: '20'
 
       - name: Install Tailwind
-        run: npm install -D tailwindcss @tailwindcss/typography
+        run: |
+          npm install -g tailwindcss @tailwindcss/typography
+          npm install -D tailwindcss @tailwindcss/typography
 
       - name: Setup Dart
         uses: dart-lang/setup-dart@v1
@@ -25,11 +27,16 @@ jobs:
 
       - name: Build Site
         run: |
-          dart run master.dart build & sleep 120 && kill $(jobs -p) || true
-          ls -R build/output
+          dart run master.dart build & 
+          sleep 120 && kill $(jobs -p) || true
+          echo "Checking Project Root:"
+          ls -F
+          echo "Checking build/output:"
+          ls -R build/output || echo "build/output not found"
 
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v4
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./build/output
+#         publish_dir: ./build/output 
+          publish_dir: ./output 
