Update deploy_to_pages.yml

diff --git a/.github/workflows/deploy_to_pages.yml b/.github/workflows/deploy_to_pages.yml
--- a/.github/workflows/deploy_to_pages.yml
+++ b/.github/workflows/deploy_to_pages.yml
@@ -21,17 +21,13 @@ jobs:
         run: |
           rm -rf ./build/output
           mkdir -p ./build/output/style
-          npm install -D tailwindcss @tailwindcss/typography
-          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
-          dart pub get 
-          npx --package tailwindcss --package @tailwindcss/typography \
-          tailwindcss -i ./input.css -o ./build/output/style/tailwind.css --minify
-          cat /home/runner/.npm/_logs/*.log
+          npm install -D tailwindcss @tailwindcss/cli @tailwindcss/typography
+          npx @tailwindcss/cli -i ./input.css -o ./build/output/style/tailwind.css --minify
+          dart pub get
           dart run master.dart build & 
-          sleep 120
-          kill $(jobs -p) || true
+          sleep 90 && kill $(jobs -p) || true
           if [ ! -f ./build/output/index.html ]; then
-             echo "index.html not found, checking for alternatives..."
+             echo "CRITICAL: index.html not found. Check master.dart paths."
              ls -R ./build/output
           fi
 
